---
# tasks file for devstack

- name: Wait 300 seconds, but only start checking after 5 seconds
  wait_for_connection:
    delay: 2
    timeout: 300

- name: Useradd stack
  become: true
  user:
    name: stack
    shell: /bin/bash
    home: /opt/stack

- name: Chmod /opt/stack
  become: true
  file:
    path: /opt/stack
    state: directory
    recurse: yes
    mode: a+x

- name: Add stack to sudoers
  become: true
  copy:
    content: "stack ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/stack

- name: Set hostname
  become: true
  shell:
    cmd: hostnamectl set-hostname "{{ standalone_hostname }}-{{ branch }}".localdomain

- name: Install pkgs
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - tmux
    - wget
    - vim
    - git

- name: Clone telemetry-tempest-plugin
  become: yes
  become_user: stack
  git:
    repo: https://opendev.org/openstack/telemetry-tempest-plugin
    dest: "$HOME/telemetry-tempest-plugin"

- name: Clone heat-tempest-plugin
  become: yes
  become_user: stack
  git:
    repo: https://opendev.org/openstack/heat-tempest-plugin
    dest: "$HOME/heat-tempest-plugin"

- name: Clone devstack
  become: yes
  become_user: stack
  git:
    repo: https://opendev.org/openstack/devstack
    dest: "$HOME/devstack"

- name: Generate local.conf
  become: yes
  become_user: stack
  template:
    src: local.conf.j2
    dest: "$HOME/devstack/local.conf"

- name: Execute stack.sh
  become: yes
  become_user: stack
  shell: "$HOME/devstack/stack.sh 2>&1 &"
  register: output
