---
- name: "Create /etc/openstack/, if it doesn't exist"
  become: true
  file:
    path: "/etc/openstack/"
    state: directory
    mode: '640'

- name: "Copy clouds.yaml to the jumphost"
  become: true
  copy:
    src: "{{ openstack_clouds_yaml }}"
    dest: "/etc/openstack/clouds.yaml"
    mode: '640'

- name: "Check that the OpenStack credentials work"
  openstack.cloud.server_info:
    cloud: "{{ openstack_cloud_name }}"
    filters: {}
    timeout: 300
  register: result

- debug:
    var: result
