---
# create VM for standalone deployment
- name: "Create the OpenStack VM"
  openstack.cloud.server:
    state: present
    cloud: "{{ openstack_cloud_name }}"
    name: "{{ standalone_vm_name }}"
    image: "{{ image_name }}"
    key_name: "{{ key_name }}"
    nics: 
      - net-name: "{{ external_network }}"
      - net-name: "{{ ctlplane_network }}"
    flavor: "{{ flavor }}"
    auto_ip: true
    timeout: 600
    userdata: |
      {%- raw -%}#!/bin/bash
      echo "net.ipv6.conf.all.disable_ipv6=1" >> /etc/sysctl.d/99-sysctl.conf
      echo "net.ipv6.conf.default.disable_ipv6=1" >> /etc/sysctl.d/99-sysctl.conf
      sysctl -p
      {% endraw %}
  register: standalone_server

- set_fact:
    standalone_user: "centos"

- name: "Debug IP address of {{ standalone_server.server.name }}({{ standalone_server.server.id }})"
  debug:
    var: standalone_server.server.accessIPv4

- name: "Set the IP address for the standalone vm"
  set_fact:
    standalone_ip: "{{ standalone_server.server.accessIPv4 }}"

- debug:
    var: standalone_ip

- name: "Create the {{ standalone_vm_name }}.inv file"
  template:
    src: standalone.inv.j2
    dest: "{{ inventory_dir }}/{{ standalone_vm_name }}.inv"
    mode: '0644'
