---
# Delete standalone vm if it exists
- name: "Remove {{ standalone_vm_name }}.inv"
  file:
    path: "{{ inventory_dir }}/{{ standalone_vm_name }}.inv"
    state: absent
  tags:
    - delete_standalone

- name: "Check server list, in case we already have it"
  openstack.cloud.server_info:
    cloud: "{{ openstack_cloud_name }}"
    server: "{{ standalone_vm_name }}"
    timeout: 300
  register: server_list
  tags:
    - delete_standalone

- name: "Delete {{ standalone_vm_name }} if exists"
  openstack.cloud.server:
    cloud: "{{ openstack_cloud_name }}"
    state: absent
    name: "{{ standalone_vm_name }}"
    timeout: 600
  when:
    - server_list.openstack_servers | length != 0
  tags:
    - delete_standalone