---
# tasks file for standalone

# check whether OSP commands execute
- include_tasks: "check_openstack.yml"

# delete standalone vm if it exists
- include_tasks: "delete_standalone.yml"

# create standalone vm
- include_tasks: "create_standalone.yml"
