---
# tasks file for standalone_configure

- name: Wait 300 seconds, but only start checking after 5 seconds
  wait_for_connection:
    delay: 2
    timeout: 300

- name: Set hostname
  become: true
  shell:
    cmd: hostnamectl set-hostname "{{ standalone_hostname }}-{{ branch }}".localdomain

- name: Install tripleo-repos-rpm
  become: true
  yum:
    name: "{{ tripleo_repos_rpm }}"
    state: present
    disable_gpg_check: yes

- name: Enable tripleo repos
  become: true
  shell:
    cmd: sudo -E tripleo-repos current-tripleo -b {{ branch }}

- name: Update system and reboot
  become: true
  yum: name=* state=latest

- name: Wait 300 seconds, but only start checking after 5 seconds
  become: true
  reboot:
    reboot_timeout: 600

- name: Install python3-tripleoclient
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - python3-tripleoclient
    - tmux
    - wget
    - vim

- name: Check if containers-prepare-parameters.yaml exists
  stat:
    path: "{{ HOME }}/containers-prepare-parameters.yaml"
  register: containers_prepare

- name: Create containers-prepare-parameter.yaml
  shell:
    cmd: "openstack tripleo container image prepare default \
  --output-env-file $HOME/containers-prepare-parameters.yaml"
  when: not containers_prepare.stat.exists

- name: Create standalone_parameters.yaml
  template:
    src: standalone_parameters.yaml.j2
    dest: "{{ HOME }}/standalone_parameters.yaml"

- name: Create deploy.sh
  template:
    src: deploy.sh.j2
    dest: "{{ HOME }}/deploy.sh"
    mode: 0755
  
- name: Execute deploy.sh
  shell:
    cmd: bash ~/deploy.sh &
